services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: go_app
    environment:
      MONGODB_URI: mongodb://root:password@mongodb:27017
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mongodb_data: