services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: go_app
    environment:
      MONGODB_URI: mongodb://root:password@mongodb:27017
      PORT: 8080
      HOST: "0.0.0.0:"
      MONGODB_DATABASE: mongodb
      MONGODB_COLLECTION: todos
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./client
    container_name: react_app
    environment:
      VITE_BASE_URL: "http://go_app:8080/api"
    ports:
      - "3000:80"
    depends_on:
      - app
    restart: unless-stopped

volumes:
  mongodb_data: